### ISSUE TITLE
[Feature] TEST코드 작성

### ISSUE THREAD

**Issue by teacherSsamko** [coding-kkanbu/teameet_backend#120]
**Is your feature request related to a problem? Please describe.**
CI를 원활하게 하기 위해 TEST코드 작성

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by hoetaek** [comment]
이거 reopen한 건 어떤 test 코드 때문이야?

**Comment by hoetaek** [comment]
* #217 
* #83

**Comment by teacherSsamko** [comment]
> 이거 reopen한 건 어떤 test 코드 때문이야?

아 이건 테스트 코드를 작성하자는 일종의 epic인데 
이거 close했던 PR은 일부 테스트코드일 뿐이어서 다시 열었어~ 우리가 합의된 수준의 테스트코드 작성에 이르기까지는 이건 열어두어야 할 것 같아~

그리고 여기서는 어느정도 수준까지 테스트 코드를 작성하면 좋을지 얘기해보면 될 것 같고

**Comment by hoetaek** [comment]
> 

오... 너무 중요한 이야기네
어느 정도까지 테스트 코드를 작성하면 좋을지 얘기 나누면 기준 있으면 정말 편하겠다
혹시 업계 표준으로 테스트 코드 작성 수준 정해진 게 따로 있어? 우리끼리 정해야 하는거지?

**Comment by hoetaek** [comment]
찾아보니까 이런 라이브러리도 있네
https://github.com/nedbat/coveragepy
심지어 우리 레파지토리에 이미 사용되고 있는듯!

몇 %의 코드가 테스트 코드로 충분히 테스트됐는지를 알려주는 툴이래
어떤 방식으로 테스트 코드 수준 이야기 해야 하는지 몰라서 가져와봤어

보통 어느 수준으로 작성하자고 이야기할 때 "모든 함수에 대해서 테스트하자", "데이터베이스에 CRUD 되는지만큼은 테스트하자" 이런 방식으로 이야기하면 되는건가?

**Comment by hoetaek** [comment]
우리 coverage 구해봤음!
![Coverage report](https://user-images.githubusercontent.com/14107090/180888289-3e5b15d7-422d-458a-b107-ebdf9dc96f5a.jpg)
![Coverage report2](https://user-images.githubusercontent.com/14107090/180888295-41da244a-44bb-4e70-a89e-5d26ed0ce5ef.jpg)

**Comment by Ridealist** [comment]
테스트코드 완료의 객관적 기준은 coverage 100% 완료!

**Comment by teacherSsamko** [comment]
100% 가능할까? ㅋㅋㅋ 
나는 Edge case를 제외하고, 새로 만든 API에 한해서는 정상적으로 작동하는지 여부 정도만 판단하면 될 것 같아.
기존에 있는 것들까지 테스트코드 작성하느라 시간을 쓸 필요는 지금은 없을 것 같구.

그리고 이후에 PR올리면 저 coverage 자동으로 돌아가게 해서 
기존 점수보다 낮으면 (새로운 API에 대한 테스트가 빠졌다는 뜻이므로) merge가 안되게 하자

**Comment by hoetaek** [comment]
> 100% 가능할까? ㅋㅋㅋ 나는 Edge case를 제외하고, 새로 만든 API에 한해서는 정상적으로 작동하는지 여부 정도만 판단하면 될 것 같아. 기존에 있는 것들까지 테스트코드 작성하느라 시간을 쓸 필요는 지금은 없을 것 같구.
> 
> 그리고 이후에 PR올리면 저 coverage 자동으로 돌아가게 해서 기존 점수보다 낮으면 (새로운 API에 대한 테스트가 빠졌다는 뜻이므로) merge가 안되게 하자

오 이것도 CI로 할 수 있는거야? 신기하다ㅋㅋㅋㅋ

**Comment by teacherSsamko** [comment]
> > 100% 가능할까? ㅋㅋㅋ 나는 Edge case를 제외하고, 새로 만든 API에 한해서는 정상적으로 작동하는지 여부 정도만 판단하면 될 것 같아. 기존에 있는 것들까지 테스트코드 작성하느라 시간을 쓸 필요는 지금은 없을 것 같구.
> > 그리고 이후에 PR올리면 저 coverage 자동으로 돌아가게 해서 기존 점수보다 낮으면 (새로운 API에 대한 테스트가 빠졌다는 뜻이므로) merge가 안되게 하자
> 
> 오 이것도 CI로 할 수 있는거야? 신기하다ㅋㅋㅋㅋ

응 ㅋㅋ 오픈소스 중에는 이걸로 테스트하는 곳들도 더러 있는거같더라구

**Comment by hoetaek** [comment]
> > > 100% 가능할까? ㅋㅋㅋ 나는 Edge case를 제외하고, 새로 만든 API에 한해서는 정상적으로 작동하는지 여부 정도만 판단하면 될 것 같아. 기존에 있는 것들까지 테스트코드 작성하느라 시간을 쓸 필요는 지금은 없을 것 같구.
> > > 그리고 이후에 PR올리면 저 coverage 자동으로 돌아가게 해서 기존 점수보다 낮으면 (새로운 API에 대한 테스트가 빠졌다는 뜻이므로) merge가 안되게 하자
> > 
> > 
> > 오 이것도 CI로 할 수 있는거야? 신기하다ㅋㅋㅋㅋ
> 
> 응 ㅋㅋ 오픈소스 중에는 이걸로 테스트하는 곳들도 더러 있는거같더라구

좋습니다!ㅋㅋㅋㅋ 어떻게 작성하는지 궁금하다

**Comment by hoetaek** [comment]
오호 https://github.com/nektos/act/pull/1243
이거 맞지? @teacherSsamko 
https://docs.codecov.com/docs
https://docs.codecov.com/docs/github-2-getting-a-codecov-account-and-uploading-coverage

**Comment by Ridealist** [comment]
- [x] social_login testcode 완성하기
- [x] #83 
- (social)/login/callback
- (social)/login/finish **추가 필요!**

**Comment by Ridealist** [comment]
수고하셨습니다! @hoetaek
