### ISSUE TITLE
[Feature]Notification detail - redirect url

### ISSUE THREAD

**Issue by Ridealist** [coding-kkanbu/teameet_backend#139]
- 현재 notification url : /api/v1/notification/2 형태로 구성
- 위 url로 get 메소드를 요청하면 api/v1/post/4 같은 게시물로 이동하는 구조
- [ ] notification이 생성될 때 url 값을 결정해 필드에 저장하는게 더 나을지?
- [ ] 프론트엔드에서 notification 객체 가져오기 더 편한 방법 생각해보기

**Comment by hoetaek** [comment]
이미 해결함
