### ISSUE TITLE
마이 페이지 api 만들기

### ISSUE THREAD

**Issue by Ridealist** [coding-kkanbu/teameet_backend#202]
- [x] #227
- [x] #228
- [x] #229

**Comment by hoetaek** [comment]
my page의 introduce 관련 필요

- [ ] user model에 introduce field 생성
- [ ] serializer에도 introduce 올 수 있도록

**Comment by Ridealist** [comment]
- [ ] 프로필 이미지 업로드 가능하도록 staticfile 디렉토리 세팅
