### ISSUE TITLE
[BUG] url 'account_login' doesn't exsist

### ISSUE THREAD

**Issue by teacherSsamko** [coding-kkanbu/teameet_backend#27]
**Describe the bug**
#26 처리 중 발생

pytest 결과
```shell
=================================== FAILURES ===================================
__________________ TestUserDetailView.test_not_authenticated ___________________

self = <kkanbu.users.tests.test_views.TestUserDetailView object at 0x7fab9145efa0>
user = <User: vickiesantiago>
rf = <django.test.client.RequestFactory object at 0x7fab91475640>

    def test_not_authenticated(self, user: User, rf: RequestFactory):
        request = rf.get("/fake-url/")
        request.user = AnonymousUser()
    
>       response = user_detail_view(request, username=user.username)

kkanbu/users/tests/test_views.py:93: 
```
```shell
>       raise NoReverseMatch(msg)
E       django.urls.exceptions.NoReverseMatch: Reverse for 'account_login' not found. 'account_login' is not a valid view function or pattern name.
```
allauth.urls에 있는 것으로 보이는 'account_login' url이 없어서 실패.

**To Reproduce**
1. config/urls.py에서 include(allauth.url) 부분 주석처리
2. `docker-compose -f local.yml run django pytest`
3. See error

**Expected behavior**
allauth package가 불필요한지 검토.
불필요하다면 url에서 제거 후, 테스트코드 수정

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. mac, window]
 - CPU: [e.g. M1, intel]

**Additional context**

**Comment by hoetaek** [comment]
allauth.urls 관련 이슈 해결함

- accounts 앱의 url에 allauth 패키지 직접 작성하여 필요한 부분들은 customizing 완료
